# Dateipfad: .github/workflows/build-cod2.yml
# Dies ist die korrigierte Version, die den 'uses'/'run'-Konflikt behebt.

name: 'Build and Push CoD2 Runtime Image'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-cod2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Schritt 1: Verwendet NUR 'uses'
      - name: 'Checkout Source Code'
        uses: actions/checkout@v4

      # Schritt 2: Verwendet NUR 'uses'
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Schritt 3: Verwendet NUR 'uses'
      - name: 'Extract metadata for Docker'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Schritt 4: Verwendet NUR 'uses' - Hier war wahrscheinlich der Fehler.
      # Dieser Block ist jetzt korrekt und enthält keine 'run'-Zeile.
      - name: 'Build and Push Docker Image'
        uses: docker/build-push-action@v5
        with:
          context: ./cod2
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
