name: Build and Push SCUM Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # DIES IST DIE ENDGÜLTIGE, KORREKTE VERSION:
          # Wir verwenden die richtige Variable 'github.repository_owner'.
          # Die Action kümmert sich um die Umwandlung in Kleinbuchstaben.
          images: ghcr.io/${{ github.repository_owner }}/docker-pelican-scum

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # DIES IST DER ENTSCHEIDENDE PUNKT:
          # Wir sagen der Action, dass sie im Ordner 'scum-server' arbeiten soll.
          context: ./scum
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
