# Dies ist der finale, vollständige Workflow zum Kopieren und Einfügen.
# Dateipfad: .github/workflows/build-and-push.yml

name: 'Build and Push Pelican CoD2 Image'

# Trigger: Startet bei Push auf den main-Branch oder manuell
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Umgebungsvariablen für den gesamten Job
env:
  # Die zu verwendende Container-Registry
  REGISTRY: ghcr.io
  # Der Name des Images. Dies wird automatisch zu "ghcr.io/DEIN_BENUTZERNAME/DEIN_REPO_NAME"
  # Um den Namen "docker-pelican-cod2" zu erhalten, benenne dein Repo entsprechend um.
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-cod2:
    # Maschine, auf der der Job läuft
    runs-on: ubuntu-latest

    # Notwendige Berechtigungen, um in die GitHub Container Registry zu pushen
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Den Quellcode aus dem Repository herunterladen
      - name: 'Checkout Source Code'
        uses: actions/checkout@v4

      # 2. An der GitHub Container Registry anmelden
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Metadaten (wie Tags und Labels) für das Docker-Image automatisch generieren
      - name: 'Extract metadata for Docker'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # 4. Das Docker-Image bauen und in die Registry hochladen
      - name: 'Build and Push Docker Image'
        uses: docker/build-push-action@v5
        with:
          # KORREKTUR: Der Kontext zeigt auf den Unterordner, in dem die Dockerfile liegt
          context: ./cod2
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Die spezifischen Argumente für den Call of Duty 2 Server
          build-args: |
            DL_URL=https://archive.org/download/cod2-linux-server/
            DL_FILE=cod2-linux-1.3.tar.bz2
            SERVER_BINARY=cod2_lnxded
